import js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'commonjs',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'writable',
        global: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        fetch: 'readonly',
        AbortSignal: 'readonly',
        AbortController: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-empty': 'off',
      'no-useless-escape': 'warn',
      'no-undef': 'error',
      'no-useless-assignment': 'warn',
      'preserve-caught-error': 'off',
    },
  },
  // Browser environment for web UI client code
  {
    files: ['src/webui/client/**/*.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        Element: 'readonly',
        HTMLElement: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        XMLHttpRequest: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        WebSocket: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        DOMParser: 'readonly',
        Range: 'readonly',
      },
    },
  },
  {
    ignores: [
      'node_modules/',
      'archive/',
      '*.json',
      '*.md',
      'eslint.config.js',
      // Obfuscated files - intentionally minified/obfuscated for distribution
      'src/evolve.js',
      'src/evolve/guards.js',
      'src/evolve/utils.js',
      'src/evolve/pipeline/collect.js',
      'src/evolve/pipeline/dispatch.js',
      'src/evolve/pipeline/enrich.js',
      'src/evolve/pipeline/hub.js',
      'src/evolve/pipeline/select.js',
      'src/evolve/pipeline/signals.js',
      // Most of src/gep is obfuscated
      'src/gep/a2aProtocol.js',
      'src/gep/candidateEval.js',
      'src/gep/candidates.js',
      'src/gep/contentHash.js',
      'src/gep/crypto.js',
      'src/gep/curriculum.js',
      'src/gep/deviceId.js',
      'src/gep/envFingerprint.js',
      'src/gep/epigenetics.js',
      'src/gep/explore.js',
      'src/gep/hash.js',
      'src/gep/hubReview.js',
      'src/gep/hubSearch.js',
      'src/gep/hubVerify.js',
      'src/gep/integrityCheck.js',
      'src/gep/learningSignals.js',
      'src/gep/memoryGraph.js',
      'src/gep/memoryGraphAdapter.js',
      'src/gep/mutation.js',
      'src/gep/narrativeMemory.js',
      'src/gep/openPRRegistry.js',
      'src/gep/personality.js',
      'src/gep/policyCheck.js',
      'src/gep/prompt.js',
      'src/gep/recallVerifier.js',
      'src/gep/reflection.js',
      'src/gep/selector.js',
      'src/gep/shield.js',
      'src/gep/skillDistiller.js',
      'src/gep/solidify.js',
      'src/gep/strategy.js',
      // Vendor/third-party minified libraries
      'src/webui/client/vendor/**/*.js',
    ],
  },
];
