/**
 * OmniQuest Media Inc.™ — CONFIDENTIAL — Proprietary
 * Cyrano™ Engine / iMagiNarratives Framework Component
 * Part of OmniSync™ Oracle Suite & Whisper Voice Twins
 * Canada-only residency | AI Advisory-Only | Immutable Provenance Hashing
 * Aligned to Business Plan v3.1 §B.3.7 & Canonical Corpus v11 (D.2)
 * Do not distribute. All rights reserved.
 */

const fs = require('fs');
const path = require('path');
const { copyHookScripts, removeHookScripts } = require('./hookAdapter');

const HOOK_SCRIPTS_DIR_NAME = 'hooks';
const PLUGINS_DIR_NAME = 'plugins';
const PLUGIN_FILE_NAME = 'evolver.js';
const EVOLVER_MARKER = '<!-- evolver-evolution-memory -->';
// First line of the plugin file. Used to (a) prove the plugin file is one we
// wrote, so uninstall can safely delete it, and (b) skip overwriting if the
// user replaced it with a custom plugin.
const PLUGIN_HEADER = '// _evolver_managed: true (do not remove this line)';

function buildPluginSource(hooksDirAbsolute) {
  // The plugin shells out to the same three Node scripts that every other
  // evolver adapter uses, so the runtime behavior stays consistent across
  // hosts. opencode loads .js files synchronously at startup and invokes
  // the default-exported async factory with a context object.
  return `${PLUGIN_HEADER}
// Auto-generated by \`evolver setup-hooks --platform=opencode\`.
// See https://opencode.ai/docs/plugins/ for the plugin API.
//
// This plugin wires opencode events to the three evolver hook scripts:
//   session.created      -> evolver-session-start.js  (inject memory)
//   tool.execute.after   -> evolver-signal-detect.js  (detect signals on writes/edits)
//   session.idle         -> evolver-session-end.js    (record outcome)
//
// Each script is a stdin/stdout JSON filter -- nothing else is shared with
// opencode, so removing this file fully detaches evolver from opencode.

const { spawnSync } = require('node:child_process');
const path = require('node:path');

const HOOKS_DIR = ${JSON.stringify(hooksDirAbsolute)};

function runHook(scriptName, payload, timeoutMs) {
  try {
    const result = spawnSync('node', [path.join(HOOKS_DIR, scriptName)], {
      input: JSON.stringify(payload || {}),
      encoding: 'utf8',
      timeout: timeoutMs,
    });
    if (!result || !result.stdout) return {};
    try { return JSON.parse(result.stdout); } catch { return {}; }
  } catch {
    return {};
  }
}

const Evolver = async () => ({
  event: async ({ event }) => {
    if (!event || typeof event.type !== 'string') return;
    if (event.type === 'session.created') {
      runHook('evolver-session-start.js', {
        session_id: event.properties && event.properties.info && event.properties.info.id,
      }, 3000);
      return;
    }
    if (event.type === 'session.idle') {
      runHook('evolver-session-end.js', {
        session_id: event.properties && event.properties.sessionID,
      }, 8000);
    }
  },
  'tool.execute.after': async (input, output) => {
    if (!input || typeof input.tool !== 'string') return;
    if (input.tool !== 'write' && input.tool !== 'edit') return;
    runHook('evolver-signal-detect.js', {
      tool_input: (output && output.args) || {},
      tool_response: (output && output.output) || (output && output.result) || {},
    }, 2000);
  },
});

module.exports = { Evolver };
module.exports.default = Evolver;
`;
}

function buildAgentsMdSection() {
  return `${EVOLVER_MARKER}
## Evolution Memory (Evolver)

This project uses evolver for self-evolution. Hooks automatically:
1. Inject recent evolution memory at session start
2. Detect evolution signals during file edits
3. Record outcomes at session end

For substantive tasks, call \`gep_recall\` before work and \`gep_record_outcome\` after.
Signals: log_error, perf_bottleneck, user_feature_request, capability_gap, deployment_issue, test_failure.`;
}

function appendSectionToFile(filePath, marker, content) {
  let existing = '';
  try {
    existing = fs.readFileSync(filePath, 'utf8');
  } catch {
    }
  checks.push({
    id: 'agents_md_section',
    ok: agentsMdHasSection,
    detail: agentsMdHasSection
      ? 'AGENTS.md contains evolution memory section'
      : 'AGENTS.md is missing or has no evolution section (re-run install)',
  });

  const allOk = checks.every(c => c.ok);

  return {
    ok: allOk,
    plugin_path: pluginPath,
    hooks_dir: hooksDir,
    config_root: configRoot,
    checks,
    note: allOk
      ? 'Plugin is installed and loadable. opencode\'s TUI "Plugins" tab will not list it -- that tab only shows TUI plugins. Run `opencode --print-logs --log-level INFO debug config` and grep for the plugin path to confirm opencode loads it at startup.'
      : 'One or more checks failed. Re-run `evolver setup-hooks --platform=opencode --force` to repair.',
  };
}

function printVerifyReport(report) {
  console.log('[opencode] Verify report');
  console.log('[opencode]   plugin path : ' + report.plugin_path);
  console.log('[opencode]   hooks dir   : ' + report.hooks_dir);
  console.log('[opencode]   config root : ' + report.config_root);
  console.log('[opencode] Checks:');
  for (const c of report.checks) {
    console.log(
      '[opencode]   ' +
        (c.ok ? '[OK]  ' : '[FAIL]') +
        ' ' +
        c.id +
        ' -- ' +
        c.detail
    );
  }
  console.log(
    '[opencode] ' + (report.ok ? 'All checks passed.' : 'Some checks failed.')
  );
  console.log('[opencode] ' + report.note);
}

function uninstall({ configRoot }) {
  const opencodeDir = path.join(configRoot, '.opencode');
  const hooksDir = path.join(opencodeDir, HOOK_SCRIPTS_DIR_NAME);
  const pluginsDir = path.join(opencodeDir, PLUGINS_DIR_NAME);
  const pluginPath = path.join(pluginsDir, PLUGIN_FILE_NAME);
  const agentsMdPath = path.join(configRoot, 'AGENTS.md');

  let changed = false;

  if (isEvolverManagedPluginFile(pluginPath)) {
    try {
      fs.unlinkSync(pluginPath);
      changed = true;
    } catch {
      /* ignore */
    }
  }

  const scripts = removeHookScripts(hooksDir);
  if (scripts > 0) changed = true;

  try {
    if (fs.existsSync(agentsMdPath)) {
      let content = fs.readFileSync(agentsMdPath, 'utf8');
      if (content.includes(EVOLVER_MARKER)) {
        const idx = content.indexOf(EVOLVER_MARKER);
        const nextSection = content.indexOf(
          '\n## ',
          idx + EVOLVER_MARKER.length
        );
        const endIdx = nextSection !== -1 ? nextSection : content.length;
        content =
          content.slice(0, idx).trimEnd() +
          (nextSection !== -1 ? content.slice(endIdx) : '');
        fs.writeFileSync(agentsMdPath, content.trimEnd() + '\n', 'utf8');
        changed = true;
      }
    }
  } catch {
    /* ignore */
  }

  console.log(
    changed
      ? '[opencode] Uninstalled evolver plugin and hooks.'
      : '[opencode] No evolver plugin found to uninstall.'
  );

  return { ok: true, removed: changed };
}

module.exports = {
  install,
  uninstall,
  verify,
  printVerifyReport,
  buildPluginSource,
  isEvolverManagedPluginFile,
  PLUGIN_FILE_NAME,
};
